name: Test

on:
  push:
    branches: [main, integration]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: Run unit tests
        run: npm run unit
      
