name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build

  test-synpress-e2e:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci   
      - name: Set Environment Variables
        run: |
          echo "NETWORK_NAME=mainnet" >> $GITHUB_ENV
          echo "SECRET_WORDS="blade blade harbor surface since fossil say police pool ribbon degree endorse"" >> $GITHUB_ENV
      - name: synpress-e2e
        run: npm run synpress
  
